import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { useTipsStore } from "@/lib/tips-store";

const categories = [{ label: "المكياج", icon: "face-retouching-natural", description: "ألوان وإطلالات يومية" }, { label: "العناية بالبشرة", icon: "auto-awesome", description: "روتين نظافة وترطيب" }, { label: "العناية بالشعر", icon: "content-cut", description: "حلول الشعر والتصفيف" }, { label: "العطور", icon: "local-florist", description: "عطور نسائية وهدايا" }, { label: "أدوات التجميل", icon: "brush", description: "فرش وإكسسوارات" }];
export default function CategoriesScreen() { const { products } = useTipsStore(); return <ScreenContainer edges={["top", "left", "right"]} containerClassName="bg-[#f7f8fc]"><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" color="#1e5fa8" size={23}/></Pressable><View><Text style={styles.title}>الأقسام</Text><Text style={styles.sub}>اختاري القسم الذي يهمك</Text></View></View><FlatList data={categories} keyExtractor={(item) => item.label} contentContainerStyle={styles.list} renderItem={({ item }) => { const count = products.filter((product) => product.category === item.label).length; return <Pressable onPress={() => router.push(`/category/${encodeURIComponent(item.label)}` as never)} style={({ pressed }) => [styles.card, pressed && { opacity: 0.85 }]}><View style={styles.icon}><MaterialIcons name={item.icon as any} color="#1e5fa8" size={28}/></View><View style={styles.copy}><Text style={styles.name}>{item.label}</Text><Text style={styles.desc}>{item.description}</Text><Text style={styles.count}>{count} منتج متاح</Text></View><MaterialIcons name="chevron-left" color="#94a3b8" size={24}/></Pressable>; }}/></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row-reverse", alignItems: "center", gap: 12, backgroundColor: "#fff", padding: 16, borderBottomWidth: 1, borderBottomColor: "#eaf0f7" }, back: { width: 40, height: 40, borderRadius: 13, backgroundColor: "#edf5fd", alignItems: "center", justifyContent: "center" }, title: { color: "#16213e", fontSize: 25, fontWeight: "900", textAlign: "right" }, sub: { color: "#718096", fontSize: 11, textAlign: "right", marginTop: 2 }, list: { padding: 16, gap: 11 }, card: { backgroundColor: "#fff", borderRadius: 18, padding: 14, borderWidth: 1, borderColor: "#eaf0f7", flexDirection: "row-reverse", alignItems: "center", gap: 12 }, icon: { width: 55, height: 55, borderRadius: 17, backgroundColor: "#edf5fd", alignItems: "center", justifyContent: "center" }, copy: { flex: 1 }, name: { color: "#16213e", fontSize: 16, fontWeight: "900", textAlign: "right" }, desc: { color: "#718096", fontSize: 11, textAlign: "right", marginTop: 3 }, count: { color: "#1e5fa8", fontSize: 10, fontWeight: "800", textAlign: "right", marginTop: 5 } });
