import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { useTipsStore } from "@/lib/tips-store";
import { fetchProfile } from "@/lib/tips-api";
export default function LoyaltyScreen() { const { session } = useTipsStore(); const [points, setPoints] = useState<number | null>(null); useEffect(() => { if (session) void fetchProfile(session).then((p) => setPoints(Number(p.beauty_points || 0))); }, [session]); return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#f7f8fc]"><ScrollView contentContainerStyle={styles.body}><View style={styles.header}><Pressable onPress={() => router.back()}><MaterialIcons name="arrow-forward" size={23} color="white" /></Pressable><Text style={styles.title}>نقاط الجمال</Text><View style={{ width: 23 }} /></View><View style={styles.card}><MaterialIcons name="stars" size={54} color="#dbeafe" /><Text style={styles.label}>رصيدك الحالي</Text><Text style={styles.points}>{points === null ? <ActivityIndicator color="white" /> : `${points.toLocaleString()} نقطة`}</Text><Text style={styles.hint}>اكتسبي نقاطاً بعد تسليم كل طلب واستخدميها في طلبك القادم.</Text></View><Text style={styles.section}>كيف يعمل النظام؟</Text>{[{ icon: "shopping-bag", title: "تسوقي منتجاتك المفضلة", text: "احصلي على نقاط مع كل طلب مكتمل." }, { icon: "redeem", title: "استبدلي نقاطك", text: "استخدمي نقاط الجمال للحصول على خصم في الدفع." }, { icon: "favorite", title: "استمتعي بمزاياك", text: "كلما تسوقت أكثر، حصلت على مزايا أفضل." }].map((item) => <View key={item.title} style={styles.row}><View style={styles.icon}><MaterialIcons name={item.icon as never} size={22} color="#1e5fa8" /></View><View style={styles.rowText}><Text style={styles.rowTitle}>{item.title}</Text><Text style={styles.rowSub}>{item.text}</Text></View></View>)}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ body: { paddingBottom: 30 }, header: { backgroundColor: "#112b52", padding: 18, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, title: { color: "white", fontSize: 21, fontWeight: "900" }, card: { backgroundColor: "#1e5fa8", margin: 16, borderRadius: 23, padding: 24, alignItems: "center" }, label: { color: "#dbeafe", marginTop: 8 }, points: { color: "white", fontSize: 30, fontWeight: "900", marginTop: 4 }, hint: { color: "#e0f2fe", textAlign: "center", lineHeight: 19, fontSize: 12, marginTop: 9 }, section: { color: "#16213e", fontSize: 18, fontWeight: "900", textAlign: "right", marginHorizontal: 16, marginTop: 5, marginBottom: 10 }, row: { backgroundColor: "white", marginHorizontal: 16, marginBottom: 9, padding: 14, borderRadius: 16, flexDirection: "row-reverse", alignItems: "center", gap: 11, borderWidth: 1, borderColor: "#eaf0f7" }, icon: { width: 42, height: 42, borderRadius: 13, backgroundColor: "#edf5fd", alignItems: "center", justifyContent: "center" }, rowText: { flex: 1 }, rowTitle: { color: "#16213e", fontWeight: "800", textAlign: "right" }, rowSub: { color: "#64748b", fontSize: 11, textAlign: "right", marginTop: 4 } });
