import { useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { useTipsStore } from "@/lib/tips-store";
import { CustomerNotification, fetchNotifications, markNotificationsRead } from "@/lib/tips-api";
export default function NotificationsScreen() { const { session } = useTipsStore(); const [items,setItems]=useState<CustomerNotification[]>([]); const [loading,setLoading]=useState(true); const load=async()=>{if(!session){setLoading(false);return;}setLoading(true);try{setItems(await fetchNotifications(session));}finally{setLoading(false);}};useEffect(()=>{void load();},[session]);const open=async(item:CustomerNotification)=>{if(session&&!item.is_read){await markNotificationsRead(session,[item.id]);setItems((current)=>current.map((x)=>x.id===item.id?{...x,is_read:true}:x));}if(item.payload?.url){router.push(item.payload.url as never);}};const markAll=async()=>{if(!session)return;await markNotificationsRead(session);setItems((current)=>current.map((x)=>({...x,is_read:true})));};const unread=items.filter((item)=>!item.is_read).length;return <ScreenContainer edges={["top","left","right"]} containerClassName="bg-[#f7f8fc]"><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={23} color="#1e5fa8"/></Pressable><View style={styles.headCopy}><Text style={styles.title}>الإشعارات</Text><Text style={styles.sub}>تحديثات الطلبات والعروض والمخزون</Text></View>{unread>0?<Pressable onPress={()=>void markAll()}><Text style={styles.mark}>قراءة الكل</Text></Pressable>:<View style={{width:52}}/>}</View>{loading?<View style={styles.loading}><ActivityIndicator color="#1e5fa8"/></View>:!session?<View style={styles.empty}><MaterialIcons name="lock-outline" size={42} color="#94a3b8"/><Text style={styles.emptyTitle}>سجلي الدخول لرؤية الإشعارات</Text><Pressable onPress={()=>router.push("/auth" as never)}><Text style={styles.link}>تسجيل الدخول</Text></Pressable></View>:<FlatList data={items} keyExtractor={(item)=>item.id} contentContainerStyle={styles.list} renderItem={({item})=><Pressable onPress={()=>void open(item)} style={({pressed})=>[styles.item,!item.is_read&&styles.unread,pressed&&{opacity:.8}]}><View style={[styles.dot,{backgroundColor:item.is_read?"#cbd5e1":"#1e5fa8"}]}/><View style={styles.copy}><View style={styles.row}><Text style={styles.itemTitle}>{item.title_ar}</Text><Text style={styles.date}>{new Date(item.created_at).toLocaleDateString("ar-EG")}</Text></View><Text style={styles.body}>{item.body_ar}</Text></View><MaterialIcons name="chevron-left" size={20} color="#94a3b8"/></Pressable>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="notifications-none" size={45} color="#94a3b8"/><Text style={styles.emptyTitle}>لا توجد إشعارات جديدة</Text><Text style={styles.emptyText}>ستظهر هنا تحديثات طلباتك وعودة المنتجات للمخزون.</Text></View>}/>}</ScreenContainer>;}
const styles=StyleSheet.create({header:{flexDirection:"row-reverse",alignItems:"center",gap:11,backgroundColor:"#fff",padding:16,borderBottomWidth:1,borderBottomColor:"#eaf0f7"},back:{width:40,height:40,borderRadius:13,backgroundColor:"#edf5fd",alignItems:"center",justifyContent:"center"},headCopy:{flex:1},title:{fontSize:23,fontWeight:"900",color:"#16213e",textAlign:"right"},sub:{fontSize:10,color:"#718096",textAlign:"right",marginTop:2},mark:{fontSize:11,fontWeight:"900",color:"#1e5fa8"},list:{padding:14,gap:9},item:{flexDirection:"row-reverse",alignItems:"flex-start",gap:10,backgroundColor:"#fff",borderRadius:16,borderWidth:1,borderColor:"#eaf0f7",padding:14},unread:{backgroundColor:"#f1f8ff",borderColor:"#cde8ff"},dot:{width:8,height:8,borderRadius:4,marginTop:6},copy:{flex:1},row:{flexDirection:"row-reverse",justifyContent:"space-between",gap:8},itemTitle:{fontSize:13,fontWeight:"900",color:"#16213e",textAlign:"right",flex:1},date:{fontSize:9,color:"#94a3b8"},body:{fontSize:11,lineHeight:17,color:"#64748b",textAlign:"right",marginTop:5},loading:{flex:1,alignItems:"center",justifyContent:"center"},empty:{margin:18,backgroundColor:"#fff",borderRadius:20,padding:35,alignItems:"center",gap:10},emptyTitle:{color:"#334155",fontSize:15,fontWeight:"900",textAlign:"center"},emptyText:{color:"#718096",fontSize:11,textAlign:"center",lineHeight:17},link:{color:"#1e5fa8",fontSize:12,fontWeight:"900"}});
