import { useState } from "react";
import { ActivityIndicator, Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import * as ImagePicker from "expo-image-picker";
import { router, useLocalSearchParams } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { uploadPaymentProof } from "@/lib/tips-api";
import { useTipsStore } from "@/lib/tips-store";
export default function PaymentProofScreen() { const { order } = useLocalSearchParams<{ order?: string }>(); const { session } = useTipsStore(); const [uri, setUri] = useState(""); const [loading, setLoading] = useState(false); const choose = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert("الصلاحية مطلوبة", "اسمحي للتطبيق بالوصول إلى الصور لاختيار إثبات الدفع."); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], quality: 0.8, allowsEditing: true }); if (!result.canceled) setUri(result.assets[0].uri); }; const submit = async () => { if (!session || !order || !uri) return Alert.alert("بيانات ناقصة", "اختاري صورة إثبات الدفع أولاً."); setLoading(true); try { await uploadPaymentProof(session, order, uri); Alert.alert("تم رفع الإثبات", "سيقوم فريق تيبس بمراجعته وتحديث حالة الدفع.", [{ text: "حسناً", onPress: () => router.replace("/orders" as never) }]); } catch (e: any) { Alert.alert("تعذر الرفع", e.message || "حاولي مرة أخرى."); } finally { setLoading(false); } }; return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#f7f8fc]"><ScrollView contentContainerStyle={styles.body}><View style={styles.header}><Pressable onPress={() => router.back()}><MaterialIcons name="arrow-forward" size={23} color="white" /></Pressable><Text style={styles.title}>إثبات الدفع</Text><View style={{ width: 23 }} /></View><View style={styles.card}><View style={styles.icon}><MaterialIcons name="receipt-long" size={32} color="#1e5fa8" /></View><Text style={styles.heading}>ارفعي صورة التحويل</Text><Text style={styles.text}>اختاري صورة واضحة لإيصال التحويل، وسيتم اعتمادها بعد مراجعة فريق الحسابات.</Text>{order ? <Text style={styles.order}>رقم الطلب: {order}</Text> : <Text style={styles.warning}>افتحي الصفحة من رسالة الطلب حتى نربط الإثبات بالطلب الصحيح.</Text>}{uri ? <Image source={{ uri }} style={styles.preview} /> : <Pressable onPress={choose} style={styles.upload}><MaterialIcons name="add-photo-alternate" size={34} color="#1e5fa8" /><Text style={styles.uploadText}>اختيار صورة من الهاتف</Text></Pressable>}<Pressable onPress={() => void submit()} disabled={loading} style={[styles.primary, loading && styles.disabled]}>{loading ? <ActivityIndicator color="white" /> : <><MaterialIcons name="cloud-upload" size={20} color="white" /><Text style={styles.primaryText}>رفع الإثبات</Text></>}</Pressable></View></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ body: { paddingBottom: 30 }, header: { backgroundColor: "#112b52", padding: 18, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, title: { color: "white", fontSize: 20, fontWeight: "900" }, card: { backgroundColor: "white", margin: 16, padding: 22, borderRadius: 22, alignItems: "center", borderWidth: 1, borderColor: "#eaf0f7" }, icon: { width: 66, height: 66, borderRadius: 21, backgroundColor: "#edf5fd", alignItems: "center", justifyContent: "center" }, heading: { color: "#16213e", fontSize: 20, fontWeight: "900", marginTop: 14 }, text: { color: "#64748b", fontSize: 12, lineHeight: 20, textAlign: "center", marginTop: 8 }, order: { color: "#1e5fa8", fontWeight: "800", marginTop: 14 }, warning: { color: "#b7791f", backgroundColor: "#fff6dc", borderRadius: 11, padding: 10, textAlign: "center", fontSize: 11, marginTop: 14 }, upload: { width: "100%", minHeight: 150, marginTop: 18, borderRadius: 15, borderWidth: 1.5, borderStyle: "dashed", borderColor: "#9fc5e8", backgroundColor: "#f7fbff", alignItems: "center", justifyContent: "center", gap: 8 }, uploadText: { color: "#1e5fa8", fontWeight: "800" }, preview: { width: "100%", height: 210, borderRadius: 15, marginTop: 18, resizeMode: "cover" }, primary: { width: "100%", marginTop: 18, backgroundColor: "#1e5fa8", borderRadius: 14, padding: 15, alignItems: "center", justifyContent: "center", flexDirection: "row-reverse", gap: 8 }, primaryText: { color: "white", fontWeight: "900" }, disabled: { opacity: 0.6 } });
