import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as Clipboard from "expo-clipboard";
import { ScreenContainer } from "@/components/screen-container";
import { useTipsStore } from "@/lib/tips-store";
import { fetchProfile, getReferralShareMessage } from "@/lib/tips-api";
export default function ReferralsScreen(){const{session}=useTipsStore();const[code,setCode]=useState("");const[loading,setLoading]=useState(true);useEffect(()=>{if(!session){setLoading(false);return;}void fetchProfile(session).then((profile)=>setCode(profile.referral_code||"")).finally(()=>setLoading(false));},[session]);const copy=async(messageOnly=false)=>{if(!code)return;await Clipboard.setStringAsync(messageOnly?getReferralShareMessage(code):code);Alert.alert("تم النسخ",messageOnly?"تم نسخ رسالة الإحالة. الصقيها في واتساب أو أي تطبيق للمشاركة.":"شاركِي الكود مع صديقاتك.");};return <ScreenContainer edges={["top","left","right"]} containerClassName="bg-[#f7f8fc]"><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><MaterialIcons name="arrow-forward" color="#1e5fa8" size={23}/></Pressable><Text style={styles.head}>كود الإحالة</Text></View>{loading?<View style={styles.loading}><ActivityIndicator color="#1e5fa8"/></View>:!session?<View style={styles.empty}><Text style={styles.emptyText}>سجلي الدخول للحصول على كودك الخاص.</Text><Pressable onPress={()=>router.push("/auth" as never)}><Text style={styles.link}>تسجيل الدخول</Text></Pressable></View>:<View style={styles.body}><View style={styles.hero}><MaterialIcons name="group-add" size={45} color="#d9efff"/><Text style={styles.kicker}>برنامج الإحالة</Text><Text style={styles.title}>شاركي الجمال واكسبي نقاطاً</Text><Text style={styles.copy}>عند اكتمال أول طلب لصديقة باستخدام كودك، تحصلين على 100 نقطة جمال.</Text><View style={styles.codeBox}><Text style={styles.code}>{code||"TIPS..."}</Text><Pressable onPress={()=>void copy()} style={styles.copyButton}><MaterialIcons name="content-copy" color="#1e5fa8" size={18}/><Text style={styles.copyButtonText}>نسخ</Text></Pressable></View></View><View style={styles.card}><Text style={styles.cardTitle}>كيف يعمل البرنامج؟</Text><Text style={styles.step}>1. انسخي كودك وأرسليه لصديقاتك.</Text><Text style={styles.step}>2. تضع الصديقة الكود عند إتمام أول طلب.</Text><Text style={styles.step}>3. تضاف النقاط بعد تسليم الطلب بنجاح.</Text></View><Pressable onPress={()=>void copy(true)} style={styles.share}><MaterialIcons name="share" size={19} color="#fff"/><Text style={styles.shareText}>نسخ رسالة الإحالة للمشاركة</Text></Pressable></View>}</ScreenContainer>}
const styles=StyleSheet.create({header:{height:68,backgroundColor:"#fff",paddingHorizontal:16,flexDirection:"row-reverse",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#eaf0f7"},back:{width:40,height:40,borderRadius:13,backgroundColor:"#edf5fd",alignItems:"center",justifyContent:"center"},head:{flex:1,textAlign:"right",fontSize:22,fontWeight:"900",color:"#16213e"},loading:{flex:1,alignItems:"center",justifyContent:"center"},body:{padding:16},hero:{backgroundColor:"#112b52",borderRadius:25,padding:23,alignItems:"flex-end"},kicker:{color:"#bfdbfe",fontWeight:"900",fontSize:11,marginTop:9},title:{color:"#fff",fontWeight:"900",fontSize:25,textAlign:"right",marginTop:6},copy:{color:"#d8e9ff",fontSize:12,lineHeight:19,textAlign:"right",marginTop:9},codeBox:{marginTop:20,width:"100%",borderRadius:16,backgroundColor:"rgba(255,255,255,.12)",padding:14,flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center"},code:{color:"#fff",fontSize:20,fontWeight:"900",letterSpacing:1.5},copyButton:{backgroundColor:"#fff",paddingVertical:8,paddingHorizontal:10,borderRadius:10,flexDirection:"row-reverse",alignItems:"center",gap:5},copyButtonText:{color:"#1e5fa8",fontWeight:"900",fontSize:11},card:{marginTop:15,backgroundColor:"#fff",borderRadius:20,padding:18,borderWidth:1,borderColor:"#eaf0f7"},cardTitle:{textAlign:"right",fontSize:16,fontWeight:"900",color:"#16213e",marginBottom:10},step:{textAlign:"right",fontSize:12,color:"#64748b",lineHeight:23},share:{marginTop:15,borderRadius:14,backgroundColor:"#1e5fa8",paddingVertical:14,flexDirection:"row-reverse",alignItems:"center",justifyContent:"center",gap:8},shareText:{color:"#fff",fontWeight:"900",fontSize:13},empty:{margin:18,backgroundColor:"#fff",borderRadius:18,padding:30,alignItems:"center",gap:12},emptyText:{color:"#64748b",textAlign:"center"},link:{color:"#1e5fa8",fontWeight:"900"}});
