import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { fetchOrders } from "@/lib/tips-api";
import { useTipsStore } from "@/lib/tips-store";
const steps = [{ key: "new", label: "تم الاستلام", icon: "schedule" }, { key: "confirmed", label: "مؤكد", icon: "check-circle" }, { key: "preparing", label: "جاري التجهيز", icon: "inventory-2" }, { key: "shipped", label: "خرج للتوصيل", icon: "local-shipping" }, { key: "delivered", label: "تم التوصيل", icon: "done-all" }];
export default function TrackOrderScreen() { const { session } = useTipsStore(); const [orders, setOrders] = useState<any[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { if (!session) { setLoading(false); return; } void fetchOrders(session).then(setOrders).catch(() => setOrders([])).finally(() => setLoading(false)); }, [session]); const order = orders[0]; const active = Math.max(0, steps.findIndex((s) => s.key === order?.status)); return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#f7f8fc]"><ScrollView contentContainerStyle={styles.body}><View style={styles.header}><Pressable onPress={() => router.back()}><MaterialIcons name="arrow-forward" size={23} color="white" /></Pressable><Text style={styles.title}>تتبع الطلب</Text><View style={{ width: 23 }} /></View>{loading ? <View style={styles.center}><ActivityIndicator color="#1e5fa8" /></View> : !session ? <View style={styles.center}><MaterialIcons name="lock-outline" size={45} color="#1e5fa8" /><Text style={styles.emptyTitle}>سجّلي الدخول لتتبع طلباتك</Text><Pressable onPress={() => router.push("/auth" as never)} style={styles.primary}><Text style={styles.primaryText}>تسجيل الدخول</Text></Pressable></View> : !order ? <View style={styles.center}><MaterialIcons name="local-shipping" size={48} color="#94a3b8" /><Text style={styles.emptyTitle}>لا توجد طلبات حتى الآن</Text><Pressable onPress={() => router.replace("/" as never)} style={styles.primary}><Text style={styles.primaryText}>تصفحي المتجر</Text></Pressable></View> : <><View style={styles.orderCard}><Text style={styles.caption}>آخر طلب</Text><Text style={styles.orderNumber}>{order.order_number}</Text><Text style={styles.date}>{new Date(order.created_at).toLocaleDateString("ar-EG")} · {Number(order.total).toLocaleString()} ج.س</Text></View><View style={styles.timeline}>{steps.map((step, index) => <View key={step.key} style={styles.step}><View style={[styles.dot, index <= active && styles.dotActive]}><MaterialIcons name={step.icon as never} size={18} color={index <= active ? "white" : "#94a3b8"} /></View><Text style={[styles.stepLabel, index <= active && styles.activeLabel]}>{step.label}</Text>{index < steps.length - 1 ? <View style={[styles.line, index < active && styles.lineActive]} /> : null}</View>)}</View><View style={styles.note}><MaterialIcons name="info-outline" size={20} color="#1e5fa8" /><Text style={styles.noteText}>تتحدث حالة الطلب تلقائياً مع كل خطوة من فريق تيبس والمندوب.</Text></View></>}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ body: { paddingBottom: 30 }, header: { backgroundColor: "#112b52", padding: 18, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, title: { color: "white", fontSize: 21, fontWeight: "900" }, center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 35, gap: 12 }, emptyTitle: { color: "#16213e", fontSize: 18, fontWeight: "900", textAlign: "center" }, primary: { backgroundColor: "#1e5fa8", borderRadius: 13, paddingHorizontal: 22, paddingVertical: 13 }, primaryText: { color: "white", fontWeight: "900" }, orderCard: { backgroundColor: "white", margin: 16, padding: 18, borderRadius: 18, borderWidth: 1, borderColor: "#eaf0f7" }, caption: { color: "#94a3b8", fontSize: 11, textAlign: "right" }, orderNumber: { color: "#16213e", fontSize: 20, fontWeight: "900", textAlign: "right", marginTop: 5 }, date: { color: "#64748b", fontSize: 12, textAlign: "right", marginTop: 7 }, timeline: { backgroundColor: "white", marginHorizontal: 16, padding: 19, borderRadius: 18, borderWidth: 1, borderColor: "#eaf0f7" }, step: { minHeight: 48, flexDirection: "row-reverse", alignItems: "center", gap: 10, position: "relative" }, dot: { width: 34, height: 34, borderRadius: 17, backgroundColor: "#f1f5f9", alignItems: "center", justifyContent: "center", zIndex: 1 }, dotActive: { backgroundColor: "#1e5fa8" }, stepLabel: { flex: 1, color: "#94a3b8", textAlign: "right", fontWeight: "700", fontSize: 13 }, activeLabel: { color: "#1e5fa8" }, line: { position: "absolute", right: 16, top: 37, height: 22, width: 2, backgroundColor: "#e2e8f0" }, lineActive: { backgroundColor: "#1e5fa8" }, note: { margin: 16, padding: 13, borderRadius: 14, backgroundColor: "#edf5fd", flexDirection: "row-reverse", gap: 8, alignItems: "center" }, noteText: { flex: 1, color: "#1e5fa8", fontSize: 11, lineHeight: 18, textAlign: "right" } });
