import type { Banner, Collection, DeliveryZone, Offer, PaymentMethod, Product } from '../../domain/entities';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    name_ar: 'سيروم حمض الهيالورونيك 2% + B5 للترطيب العميق',
    name_en: 'Hyaluronic Acid 2% + B5 Hydrating Serum',
    price: 18500,
    discountPercentage: 10,
    effectivePrice: 16650,
    pricingRule: { kind: 'discount', label: 'خصم 10%' },
    category: 'العناية بالبشرة',
    brand: 'The Ordinary',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80',
      'https://images.unsplash.com/photo-1608248597359-009581f3b397?w=800&q=80',
    ],
    description: 'سيروم عالي التركيز بحمض الهيالورونيك النقي وفيتامين B5 لتجديد مرونة البشرة وترطيبها بعمق على عدة مستويات.',
    benefits: ['ترطيب مكثف وعميق طوال اليوم', 'دعم حاجز الرطوبة الطبيعي للبشرة', 'تحسين مظهر الخطوط الدقيقة'],
    ingredients: ['Aqua (Water)', 'Sodium Hyaluronate', 'Panthenol', 'Ahnfeltia Concinna Extract', 'Glycerin'],
    usage: 'ضعي بضع قطرات على الوجه صباحاً ومساءً قبل الكريمات الثقيلة.',
    origin: 'كندا',
    expiry: '2027-12',
    stock: 25,
    isImported: true,
    skinType: ['جافة', 'عادية', 'مختلطة', 'دهنية', 'حساسة'],
    rating: 4.8,
    reviewCount: 36,
    variants: [
      { id: 'v-1-30ml', name_ar: '30 مل', name_en: '30ml', price: 18500, effectivePrice: 16650, pricingRule: { kind: 'discount', label: 'خصم 10%' } },
      { id: 'v-1-60ml', name_ar: '60 مل', name_en: '60ml', price: 32000, effectivePrice: 28800, pricingRule: { kind: 'discount', label: 'خصم 10%' } },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-002',
    name_ar: 'غسول الوجه الرغوي للبشرة العادية إلى الدهنية',
    name_en: 'Foaming Facial Cleanser',
    price: 24000,
    discountPercentage: 0,
    effectivePrice: 24000,
    pricingRule: null,
    category: 'العناية بالبشرة',
    brand: 'CeraVe',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80',
    ],
    description: 'غسول لطيف يزيل الزيوت الزائدة والمكياج دون الإخلال بالحاجز الواقي الطبيعي للبشرة.',
    benefits: ['ينظف ويزيل الزيوت بلطف', 'يحتوي على 3 سيراميدات أساسية', 'حمض النياسيناميد لتهدئة البشرة'],
    ingredients: ['Ceramides 1, 3, 6-II', 'Hyaluronic Acid', 'Niacinamide', 'Glycerin'],
    usage: 'دلكي الغسول على بشرة رطبة بحركات دائرية ثم اشطفيه بالماء الفاتر.',
    origin: 'الولايات المتحدة',
    expiry: '2028-06',
    stock: 18,
    isImported: true,
    skinType: ['دهنية', 'مختلطة', 'عادية'],
    rating: 4.9,
    reviewCount: 52,
    variants: [
      { id: 'v-2-236ml', name_ar: '236 مل', name_en: '236ml', price: 24000, effectivePrice: 24000, pricingRule: null },
      { id: 'v-2-473ml', name_ar: '473 مل', name_en: '473ml', price: 39500, effectivePrice: 39500, pricingRule: null },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-003',
    name_ar: 'أحمر شفاه سائل مات سوبر ستاي إنك يدوم طويلاً',
    name_en: 'SuperStay Matte Ink Liquid Lipstick',
    price: 14500,
    discountPercentage: 15,
    effectivePrice: 12325,
    pricingRule: { kind: 'discount', label: 'خصم 15%' },
    category: 'المكياج',
    brand: 'Maybelline',
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80',
    ],
    description: 'أحمر شفاه سائل بتركيبة مات غنية تدوم حتى 16 ساعة متواصلة دون تلطخ أو جفاف بفضل دقة أداة التطبيق السهمية.',
    benefits: ['ثبات يدوم حتى 16 ساعة', 'تغطية كاملة من تمريرة واحدة', 'ألوان مشبعة ومقاومة للتلطخ'],
    ingredients: ['Dimethicone', 'Isododecane', 'Color Pigments'],
    usage: 'ضعيه على الشفتين ابتداءً من المنتصف واتركيه يجف لبضع ثوانٍ للحصول على لمسة نهائية غير لامعة.',
    origin: 'الولايات المتحدة',
    expiry: '2027-09',
    stock: 40,
    isImported: true,
    skinType: ['جميع أنواع البشرة'],
    rating: 4.7,
    reviewCount: 28,
    variants: [
      { id: 'v-3-pioneer', name_ar: 'أحمر كلاسيكي (Pioneer)', name_en: 'Pioneer', price: 14500, effectivePrice: 12325, pricingRule: { kind: 'discount', label: 'خصم 15%' } },
      { id: 'v-3-lover', name_ar: 'وردي ناعم (Lover)', name_en: 'Lover', price: 14500, effectivePrice: 12325, pricingRule: { kind: 'discount', label: 'خصم 15%' } },
      { id: 'v-3-seducer', name_ar: 'نيود دافئ (Seductress)', name_en: 'Seductress', price: 14500, effectivePrice: 12325, pricingRule: { kind: 'discount', label: 'خصم 15%' } },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-004',
    name_ar: 'ماسك الشفاه الليلي بالتوت للترطيب الفائق',
    name_en: 'Lip Sleeping Mask Berry',
    price: 19000,
    discountPercentage: 0,
    effectivePrice: 19000,
    pricingRule: null,
    category: 'العناية بالبشرة',
    brand: 'Laneige',
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80',
    ],
    description: 'قناع شفاه ليلي يذيب خلايا الجلد الميتة بلطف ويمنح الشفاه ترطيباً مكثفاً طوال الليل بمستخلصات التوت وفيتامين C.',
    benefits: ['ترطيب فائق وعميق', 'غني بمضادات الأكسدة وفيتامين C', 'شفاه ناعمة وممتلئة'],
    ingredients: ['Berry Fruit Complex', 'Vitamin C', 'Coconut Oil'],
    usage: 'ضعي كمية وفيرة على الشفاه قبل النوم وامسحي الفائض في الصباح بمنديل.',
    origin: 'كوريا الجنوبية',
    expiry: '2028-01',
    stock: 12,
    isImported: true,
    skinType: ['جميع أنواع البشرة'],
    rating: 5.0,
    reviewCount: 41,
    variants: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-005',
    name_ar: 'زيت الأرغان العضوي النقي للشعر والبشرة',
    name_en: 'Pure Organic Argan Oil',
    price: 16000,
    discountPercentage: 20,
    effectivePrice: 12800,
    pricingRule: { kind: 'discount', label: 'خصم 20%' },
    category: 'العناية بالشعر',
    brand: 'Tips Beauty Lab',
    image: 'https://images.unsplash.com/photo-1608248597359-009581f3b397?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1608248597359-009581f3b397?w=800&q=80',
    ],
    description: 'زيت أرغان نقي 100% معصور على البارد يغذي بصيلات الشعر ويمنح أطرافه لمعاناً ويساعد في ترطيب البشرة الجافة.',
    benefits: ['تغذية وترطيب أطراف الشعر الجاف', 'مكافحة التقصف', 'إضفاء لمعان ونعومة حريرية'],
    ingredients: ['100% Argania Spinosa Kernel Oil'],
    usage: 'وزعي قطرات قليلة على أطراف الشعر المبلل أو الجاف أو طبقي قطرات على الوجه والرقبة.',
    origin: 'المغرب',
    expiry: '2027-11',
    stock: 30,
    isImported: false,
    skinType: ['جافة', 'عادية'],
    rating: 4.9,
    reviewCount: 19,
    variants: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-006',
    name_ar: 'عطر مسك الفانيليا والعنبر الفاخر المركز',
    name_en: 'Vanilla & Amber Luxury Musk',
    price: 35000,
    discountPercentage: 0,
    effectivePrice: 35000,
    pricingRule: null,
    category: 'العطور',
    brand: 'Tips Signature',
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&q=80',
    ],
    description: 'توليفة شرقية ساحرة تجمع بين نقاء المسك الأبيض ودفء الفانيليا المدغشقرية والعنبر الفاخر مع ثبات استثنائي.',
    benefits: ['ثبات يدوم طويلاً', 'فوحان راقٍ غير مزعج', 'مناسب لجميع المناسبات'],
    ingredients: ['Alcohol Denat', 'Parfum', 'Aqua', 'Musk Oil'],
    usage: 'رشي على أماكن النبض مثل المعصمين وخلف الأذنين والرقبة.',
    origin: 'السودان',
    expiry: '2029-01',
    stock: 15,
    isImported: false,
    skinType: ['جميع أنواع البشرة'],
    rating: 4.8,
    reviewCount: 22,
    variants: [
      { id: 'v-6-50ml', name_ar: '50 مل', name_en: '50ml', price: 35000, effectivePrice: 35000, pricingRule: null },
      { id: 'v-6-100ml', name_ar: '100 مل', name_en: '100ml', price: 58000, effectivePrice: 58000, pricingRule: null },
    ],
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_COLLECTIONS: Collection[] = [
  {
    id: 'col-best-sellers',
    slug: 'best-sellers',
    name_ar: 'الأكثر مبيعاً',
    description_ar: 'المنتجات الأكثر طلباً وإعجاباً من عميلاتنا في السودان',
    icon: 'sparkles',
    displayOrder: 1,
    productIds: ['prod-001', 'prod-002', 'prod-003', 'prod-006'],
  },
  {
    id: 'col-skincare-essentials',
    slug: 'skincare',
    name_ar: 'أساسيات العناية اليومية',
    description_ar: 'مجموعة متكاملة لبشرة نضرة وصحية طوال اليوم',
    icon: 'heart',
    displayOrder: 2,
    productIds: ['prod-001', 'prod-002', 'prod-004'],
  },
  {
    id: 'col-discounts',
    slug: 'discounts',
    name_ar: 'عروض حصرية',
    description_ar: 'أفضل الخصومات والتخفيضات على منتجات مختارة',
    icon: 'percent',
    displayOrder: 3,
    productIds: ['prod-001', 'prod-003', 'prod-005'],
  },
];

export const MOCK_BANNERS: Banner[] = [
  {
    id: 'b-1',
    title_ar: 'تشكيلة العناية الفاخرة لبشرة مشرقة',
    subtitle_ar: 'أفضل المنتجات العالمية الأصلية المختارة بعناية',
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1200&q=80',
    actionType: 'category',
    actionValue: 'العناية بالبشرة',
  },
  {
    id: 'b-2',
    title_ar: 'ألوان وجاذبية مع تشكيلة المكياج الحديثة',
    subtitle_ar: 'إطلالات تناسب جميع المناسبات بأفضل الأسعار',
    imageUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=1200&q=80',
    actionType: 'category',
    actionValue: 'المكياج',
  },
];

export const MOCK_OFFERS: Offer[] = [
  {
    id: 'offer-1',
    title: 'تخفيضات موسم الجمال',
    description: 'خصم حتى 20% على منتجات مختارة من العناية بالبشرة والشعر',
    discountType: 'percentage',
    discountValue: 20,
    targetKind: 'all',
    targetValue: null,
    endsAt: new Date(Date.now() + 7 * 86400000).toISOString(),
    productIds: ['prod-001', 'prod-003', 'prod-005'],
  },
];

export const MOCK_DELIVERY_ZONES: DeliveryZone[] = [
  { id: 'zone-krt-1', name: 'الخرطوم', state: 'الخرطوم', fee: 3000 },
  { id: 'zone-krt-2', name: 'أم درمان', state: 'الخرطوم', fee: 3000 },
  { id: 'zone-krt-3', name: 'بحري', state: 'الخرطوم', fee: 3000 },
  { id: 'zone-pts-1', name: 'بورتسودان', state: 'البحر الأحمر', fee: 4000 },
  { id: 'zone-krm-1', name: 'كسلا', state: 'كسلا', fee: 4500 },
  { id: 'zone-gdr-1', name: 'القضارف', state: 'القضارف', fee: 4500 },
  { id: 'zone-jaz-1', name: 'مدني', state: 'الجزيرة', fee: 4000 },
];

export const MOCK_PAYMENT_METHODS: PaymentMethod[] = [
  { code: 'COD', nameAr: 'الدفع عند الاستلام', descriptionAr: 'الدفع نقداً عند استلام طلبك', requiresProof: false, accountDetails: {} },
  { code: 'MYCASHI', nameAr: 'ماي كاشي', descriptionAr: 'التحويل عبر رقم ماي كاشي وإرفاق إشعار التحويل', requiresProof: true, accountDetails: { 'رقم الحساب': '0912345678' } },
];
