import { Alert, FlatList, Image, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { useTipsStore } from "@/lib/tips-store";
import { getCartItemCount } from "@/lib/cart-utils";
import { getDiscountedPrice } from "@/lib/tips-api";

export default function CartScreen() {
  const { cart, setQuantity } = useTipsStore();
  const itemCount = getCartItemCount(cart);
  const subtotal = cart.reduce((sum, item) => sum + getDiscountedPrice(item) * item.quantity, 0);
  const removeItem = (id: string, name: string) => Alert.alert("حذف من السلة", `هل تريدين حذف ${name} من السلة؟`, [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => void setQuantity(id, 0) }]);

  return <ScreenContainer edges={["top", "left", "right"]} containerClassName="bg-[#f7f8fc]"><View style={styles.wrap}>
    <View style={styles.header}><Text style={styles.title}>سلة التسوق</Text><Text style={styles.subtitle}>{itemCount ? `${itemCount} قطعة في السلة` : "السلة فارغة"}</Text></View>
    <FlatList data={cart} keyExtractor={(item) => item.id} contentContainerStyle={cart.length ? styles.list : styles.emptyList} ListEmptyComponent={<View style={styles.empty}><View style={styles.emptyIcon}><MaterialIcons name="shopping-cart" size={43} color="#1e5fa8" /></View><Text style={styles.emptyTitle}>سلتك فارغة</Text><Text style={styles.emptyText}>أضيفي المنتجات التي تريدينها من الصفحة الرئيسية.</Text><Pressable accessibilityRole="button" onPress={() => router.replace("/")} style={styles.browse}><Text style={styles.browseText}>تصفحي المنتجات</Text></Pressable></View>} renderItem={({ item }) => <View style={styles.item}>{item.image ? <Image source={{ uri: item.image }} style={styles.image} resizeMode="cover" /> : <View style={[styles.image, styles.placeholder]}><MaterialIcons name="auto-awesome" size={34} color="#1e5fa8" /></View>}<View style={styles.details}><View style={styles.itemTop}><Pressable accessibilityRole="button" accessibilityLabel={`حذف ${item.name_ar} من السلة`} onPress={() => removeItem(item.id, item.name_ar)} style={({ pressed }) => [styles.delete, pressed && styles.pressed]}><MaterialIcons name="delete-outline" size={22} color="#dc426d" /></Pressable><View style={styles.copy}><Text numberOfLines={2} style={styles.name}>{item.name_ar}</Text><Text numberOfLines={1} style={styles.brand}>{item.brand || "TIPS Beauty"}</Text></View></View><View style={styles.itemBottom}><Text style={styles.price}>{getDiscountedPrice(item).toLocaleString()} ج.س</Text><View style={styles.quantity}><Pressable accessibilityRole="button" accessibilityLabel={`تقليل كمية ${item.name_ar}`} onPress={() => void setQuantity(item.id, item.quantity - 1)} style={({ pressed }) => [styles.qtyButton, pressed && styles.pressed]}><MaterialIcons name="remove" size={19} color="#1e5fa8" /></Pressable><Text accessibilityLabel={`الكمية ${item.quantity}`} style={styles.qty}>{item.quantity}</Text><Pressable accessibilityRole="button" accessibilityLabel={`زيادة كمية ${item.name_ar}`} onPress={() => void setQuantity(item.id, item.quantity + 1)} style={({ pressed }) => [styles.qtyButton, pressed && styles.pressed]}><MaterialIcons name="add" size={19} color="#1e5fa8" /></Pressable></View></View></View></View>} />
    {cart.length ? <View style={styles.footer}><View style={styles.totalRow}><Text style={styles.totalLabel}>الإجمالي التقديري</Text><Text style={styles.total}>{subtotal.toLocaleString()} ج.س</Text></View><Text style={styles.delivery}>رسوم التوصيل والخصومات تحسب عند التأكيد.</Text><Pressable accessibilityRole="button" onPress={() => router.push("/checkout")} style={({ pressed }) => [styles.checkout, pressed && styles.pressed]}><Text style={styles.checkoutText}>متابعة إلى إتمام الطلب</Text><MaterialIcons name="arrow-back" size={20} color="white"/></Pressable></View> : null}
  </View></ScreenContainer>;
}

const styles = StyleSheet.create({
  wrap: { flex: 1 }, header: { padding: 20, backgroundColor: "#112b52" }, title: { color: "#fff", textAlign: "right", fontSize: 25, fontWeight: "900" }, subtitle: { color: "#cbdcf4", textAlign: "right", marginTop: 5, fontSize: 12 }, list: { padding: 16, gap: 13, paddingBottom: 174 }, emptyList: { flexGrow: 1, justifyContent: "center", padding: 24 }, item: { minHeight: 132, backgroundColor: "#fff", padding: 11, borderRadius: 18, flexDirection: "row-reverse", gap: 12, borderWidth: 1, borderColor: "#e7edf5" }, image: { width: 108, height: 108, borderRadius: 14, backgroundColor: "#e7eef8" }, placeholder: { alignItems: "center", justifyContent: "center" }, details: { flex: 1, minHeight: 108, justifyContent: "space-between" }, itemTop: { flexDirection: "row", gap: 8 }, copy: { flex: 1, alignItems: "flex-end" }, name: { color: "#16213e", fontWeight: "900", textAlign: "right", lineHeight: 19, fontSize: 14 }, brand: { color: "#94a3b8", textAlign: "right", fontSize: 10, marginTop: 4 }, delete: { width: 36, height: 36, borderRadius: 11, backgroundColor: "#fff1f4", alignItems: "center", justifyContent: "center" }, itemBottom: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", gap: 8 }, price: { color: "#1e5fa8", fontWeight: "900", fontSize: 14, flex: 1, textAlign: "right" }, quantity: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "#edf5fd", borderRadius: 11, padding: 4 }, qtyButton: { width: 30, height: 30, borderRadius: 9, backgroundColor: "#fff", alignItems: "center", justifyContent: "center" }, qty: { color: "#16213e", fontWeight: "900", minWidth: 20, textAlign: "center", fontSize: 14 }, footer: { position: "absolute", left: 0, right: 0, bottom: 0, padding: 16, paddingBottom: 17, backgroundColor: "#fff", borderTopWidth: 1, borderTopColor: "#e5eaf1" }, totalRow: { flexDirection: "row-reverse", justifyContent: "space-between" }, totalLabel: { fontSize: 15, fontWeight: "900", color: "#16213e" }, total: { fontSize: 18, fontWeight: "900", color: "#1e5fa8" }, delivery: { textAlign: "right", color: "#718096", fontSize: 11, marginTop: 5 }, checkout: { marginTop: 13, flexDirection: "row", justifyContent: "center", gap: 8, alignItems: "center", backgroundColor: "#1e5fa8", padding: 14, borderRadius: 13 }, checkoutText: { color: "#fff", fontWeight: "900" }, empty: { alignItems: "center", gap: 9 }, emptyIcon: { width: 80, height: 80, borderRadius: 26, backgroundColor: "#edf5fd", alignItems: "center", justifyContent: "center" }, emptyTitle: { fontSize: 20, fontWeight: "900", color: "#16213e", marginTop: 6 }, emptyText: { color: "#64748b", textAlign: "center" }, browse: { marginTop: 10, backgroundColor: "#1e5fa8", paddingHorizontal: 20, paddingVertical: 11, borderRadius: 12 }, browseText: { color: "#fff", fontWeight: "900" }, pressed: { opacity: 0.8, transform: [{ scale: 0.98 }] },
});
