import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Image, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { fetchOrders, fetchReviewableOrderItems, type ReviewableOrderItem } from "@/lib/tips-api";
import { shouldShowReviewPrompt } from "@/lib/review-reminder";
import { useTipsStore } from "@/lib/tips-store";

type Order = { id: string; order_number: string; total: number; status: string; payment_status: string; created_at: string };
const labels: Record<string, string> = { new: "تم الاستلام", confirmed: "مؤكد", preparing: "جاري التجهيز", shipped: "خرج للتوصيل", delivered: "تم التوصيل", cancelled: "ملغي", delivery_failed: "تعذر التسليم" };

export default function OrdersScreen() {
  const { session, configured } = useTipsStore();
  const [orders, setOrders] = useState<Order[]>([]);
  const [reviewable, setReviewable] = useState<ReviewableOrderItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const load = async () => {
    if (!session) return;
    setLoading(true); setError("");
    try {
      const [nextOrders, nextReviewable] = await Promise.all([fetchOrders(session) as Promise<Order[]>, fetchReviewableOrderItems(session)]);
      setOrders(nextOrders); setReviewable(nextReviewable);
    } catch (e: any) { setError(e.message || "تعذر تحميل الطلبات."); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, [session]);
  const reviewableByOrder = useMemo(() => reviewable.reduce<Record<string, ReviewableOrderItem[]>>((grouped, item) => ({ ...grouped, [item.order_id]: [...(grouped[item.order_id] || []), item] }), {}), [reviewable]);

  if (!session) return <ScreenContainer className="p-5" containerClassName="bg-[#f7f8fc]"><View style={styles.empty}><MaterialIcons name="receipt-long" size={44} color="#1e5fa8"/><Text style={styles.title}>سجل طلباتك</Text><Text style={styles.text}>سجّلي الدخول لمتابعة حالة الطلبات والدفع والتوصيل.</Text></View></ScreenContainer>;
  return <ScreenContainer edges={["top", "left", "right"]} containerClassName="bg-[#f7f8fc]"><View style={styles.screen}><View style={styles.header}><Text style={styles.headerTitle}>طلباتي</Text><Pressable accessibilityRole="button" accessibilityLabel="تحديث الطلبات" onPress={() => void load()} style={({ pressed }) => [styles.refresh, pressed && styles.pressed]}><MaterialIcons name="refresh" size={23} color="#1e5fa8"/></Pressable></View>{loading ? <View style={styles.loading}><ActivityIndicator color="#1e5fa8"/></View> : <FlatList data={orders} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="inventory-2" size={44} color="#94a3b8"/><Text style={styles.title}>{configured ? "لا توجد طلبات حتى الآن" : "أكملي ربط التطبيق أولاً"}</Text>{error ? <Text style={styles.error}>{error}</Text> : <Text style={styles.text}>بعد إتمام أول طلب سيظهر هنا مع حالته.</Text>}</View>} renderItem={({ item }) => { const orderItems = reviewableByOrder[item.id] || []; return <View style={styles.card}><View style={styles.row}><View><Text style={styles.number}>{item.order_number}</Text><Text style={styles.date}>{new Date(item.created_at).toLocaleDateString("ar-EG")}</Text></View><View style={[styles.badge, item.status === "delivered" && styles.deliveredBadge]}><Text style={[styles.badgeText, item.status === "delivered" && styles.deliveredBadgeText]}>{labels[item.status] || item.status}</Text></View></View><View style={[styles.row, { marginTop: 16 }]}><Text style={styles.payment}>{item.payment_status === "paid" ? "تم الدفع" : "بانتظار الدفع"}</Text><Text style={styles.total}>{Number(item.total).toLocaleString()} ج.س</Text></View>{shouldShowReviewPrompt(item.status, orderItems.length) ? <View style={styles.reviewBlock}><View style={styles.reviewHeading}><MaterialIcons name="rate-review" size={18} color="#1e5fa8" /><Text style={styles.reviewTitle}>شاركي رأيك في المنتجات المستلمة</Text></View>{orderItems.map((product) => <View key={product.product_id} style={styles.reviewProduct}>{product.product_image ? <Image source={{ uri: product.product_image }} style={styles.reviewImage} /> : <View style={styles.reviewImage}><MaterialIcons name="auto-awesome" size={20} color="#1e5fa8" /></View>}<Text numberOfLines={2} style={styles.reviewName}>{product.product_name_ar}</Text>{product.has_review ? <View style={styles.doneReview}><MaterialIcons name="check" size={15} color="#17835e" /><Text style={styles.doneReviewText}>تم التقييم</Text></View> : <Pressable accessibilityRole="button" onPress={() => router.push({ pathname: "/review/[orderId]", params: { orderId: product.order_id, productId: product.product_id } } as never)} style={({ pressed }) => [styles.reviewButton, pressed && styles.pressed]}><Text style={styles.reviewButtonText}>قيّمي المنتج</Text></Pressable>}</View>)}</View> : null}</View>; }}/>}</View></ScreenContainer>;
}

const styles = StyleSheet.create({
  screen: { flex: 1 }, header: { backgroundColor: "#112b52", padding: 20, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, headerTitle: { color: "white", fontWeight: "900", fontSize: 24 }, refresh: { width: 38, height: 38, borderRadius: 12, backgroundColor: "#fff", alignItems: "center", justifyContent: "center" }, loading: { flex: 1, justifyContent: "center", alignItems: "center" }, list: { padding: 16, gap: 12, paddingBottom: 34 }, card: { backgroundColor: "white", borderRadius: 18, padding: 16, borderWidth: 1, borderColor: "#edf1f7" }, row: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, number: { color: "#16213e", fontWeight: "900", textAlign: "right" }, date: { color: "#94a3b8", marginTop: 4, fontSize: 12 }, badge: { backgroundColor: "#e7f0fb", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 }, deliveredBadge: { backgroundColor: "#ecfdf5" }, badgeText: { color: "#1e5fa8", fontWeight: "800", fontSize: 11 }, deliveredBadgeText: { color: "#17835e" }, payment: { color: "#64748b", fontSize: 12 }, total: { color: "#1e5fa8", fontWeight: "900" }, reviewBlock: { marginTop: 16, paddingTop: 14, borderTopWidth: 1, borderTopColor: "#edf1f7", gap: 9 }, reviewHeading: { flexDirection: "row-reverse", alignItems: "center", gap: 6 }, reviewTitle: { color: "#1e5fa8", fontSize: 12, fontWeight: "900" }, reviewProduct: { minHeight: 54, flexDirection: "row-reverse", alignItems: "center", gap: 9, backgroundColor: "#f7faff", borderRadius: 12, padding: 7 }, reviewImage: { width: 40, height: 40, borderRadius: 9, backgroundColor: "#eaf2fb", alignItems: "center", justifyContent: "center" }, reviewName: { flex: 1, color: "#334155", fontSize: 11, fontWeight: "800", textAlign: "right" }, reviewButton: { backgroundColor: "#1e5fa8", borderRadius: 9, paddingHorizontal: 9, paddingVertical: 7 }, reviewButtonText: { color: "#fff", fontSize: 10, fontWeight: "900" }, doneReview: { flexDirection: "row-reverse", gap: 3, alignItems: "center", paddingHorizontal: 8 }, doneReviewText: { color: "#17835e", fontSize: 10, fontWeight: "900" }, empty: { alignItems: "center", justifyContent: "center", flex: 1, padding: 28, gap: 10 }, title: { fontWeight: "900", color: "#16213e", fontSize: 20 }, text: { color: "#64748b", textAlign: "center", lineHeight: 21 }, error: { color: "#dc2626", textAlign: "center" }, pressed: { opacity: 0.8, transform: [{ scale: 0.98 }] },
});
