#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Launch configuration for TIPS Beauty. Reference: docs/AUDIT-REPORT.md §6.
# Run from the repo root:  bash scripts/launch-wizard.sh
# Non-secret values are remembered in .env.launch.local (gitignored). Secrets go
# straight to Supabase Edge Function secrets via the logged-in CLI, never to disk.

ENV_FILE=".env.launch.local"
PROJECT_REF="eaomyiihsuikinkdhwzy"
SUPABASE_URL="https://${PROJECT_REF}.supabase.co"
DASH="https://supabase.com/dashboard/project/${PROJECT_REF}"
STOREFRONT_URL="https://beauty.tips-sd.com"
ADMIN_URL="https://admin.beauty.tips-sd.com"

# set_fn_secret NAME VALUE writes an Edge Function secret with the Supabase CLI.
set_fn_secret() {
  local name="$1" value="$2"
  if npx supabase secrets set "${name}=${value}" >/dev/null 2>&1; then
    printf '  %s✓ set%s Edge Function secret %s\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Edge Function secret $name (Dashboard → Edge Functions → Secrets)")
    warn "could not set $name via CLI; add it in the dashboard"
  fi
}

TOTAL_STAGES=11

banner "TIPS Beauty launch configuration"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Gemini API key (beauty-advice chat)"
say "The beauty chat runs server-side and needs a Google Gemini key."
open_url "https://aistudio.google.com/app/apikey"
step "Click 'Create API key', pick or create a Google Cloud project, copy the key."
ask_secret GEMINI_API_KEY "Paste the Gemini API key (Enter to skip):"
[[ -n "$GEMINI_API_KEY" ]] && set_fn_secret GEMINI_API_KEY "$GEMINI_API_KEY"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Resend API key (transactional email)"
say "Order confirmations and staff alerts are sent through Resend."
open_url "https://resend.com/api-keys"
step "Sign in (create the account if needed) → 'Create API Key' → Full access → copy it."
ask_secret RESEND_API_KEY "Paste the Resend API key (Enter to skip):"
[[ -n "$RESEND_API_KEY" ]] && set_fn_secret RESEND_API_KEY "$RESEND_API_KEY"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Resend domain + DNS for tips-sd.com"
say "Mail from orders@tips-sd.com is only delivered once the domain is verified."
open_url "https://resend.com/domains"
step "Click 'Add Domain' → enter tips-sd.com → choose the EU region."
step "Resend shows DNS records (MX + TXT for SPF and DKIM). Keep that page open."
step "Open your DNS host for tips-sd.com and add every record exactly as shown."
ask DNS_HOST "Which DNS host manages tips-sd.com (e.g. Cloudflare, GoDaddy)?"
write_env DNS_HOST "$DNS_HOST"
note "DNS can take up to an hour to propagate."
pause "Press Enter once the records are added; then click 'Verify' in Resend."
if confirm "Does Resend show the domain as Verified?"; then
  write_env RESEND_DOMAIN_VERIFIED "yes"
else
  write_env RESEND_DOMAIN_VERIFIED "pending"
  SKIPPED+=("Resend domain verification for tips-sd.com (re-check https://resend.com/domains)")
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Email function configuration"
say "The send-order-emails function is called by a database job with a shared key."
CRON_SECRET=""
if [[ -n "$(_existing CRON_SECRET_SET || true)" ]]; then
  warn "A CRON_SECRET was set on $(_existing CRON_SECRET_SET); a new one requires re-running the Vault stage."
  confirm "Generate a new CRON_SECRET?" && CRON_SECRET="new"
else
  CRON_SECRET="new"
fi
if [[ "$CRON_SECRET" == "new" ]]; then
  CRON_SECRET=$(openssl rand -hex 24 2>/dev/null || head -c 48 /dev/urandom | od -An -tx1 | tr -d ' \n')
  set_fn_secret CRON_SECRET "$CRON_SECRET"
  write_env CRON_SECRET_SET "$(date +%F)"
  printf '\n  %sCRON_SECRET — copy it for the next stage:%s %s\n\n' "$BOLD" "$RESET" "$CRON_SECRET"
fi
ask EMAIL_FROM "Sender shown to customers [TIPS Beauty <orders@tips-sd.com>]:"
EMAIL_FROM="${EMAIL_FROM:-TIPS Beauty <orders@tips-sd.com>}"
write_env EMAIL_FROM "$EMAIL_FROM"
set_fn_secret EMAIL_FROM "$EMAIL_FROM"
set_fn_secret ADMIN_PORTAL_URL "$ADMIN_URL"
set_fn_secret ALLOWED_ORIGINS "${STOREFRONT_URL},${ADMIN_URL}"
write_env ALLOWED_ORIGINS "${STOREFRONT_URL},${ADMIN_URL}"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Vault secrets (lets the database job call the email function)"
say "Paste the following into the SQL editor and run it:"
open_url "${DASH}/sql/new"
printf '\n'
say "select vault.create_secret('<CRON_SECRET from the previous stage>', 'send_order_emails_key');"
say "select vault.create_secret('${SUPABASE_URL}/functions/v1/send-order-emails', 'send_order_emails_url');"
printf '\n'
note "If a secret already exists, update it instead:"
note "  select vault.update_secret(id, '<new value>') from vault.secrets where name = 'send_order_emails_key';"
pause "Press Enter once the query ran successfully."
write_env VAULT_SECRETS_SET "$(date +%F)"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Supabase Auth: SMTP via Resend"
say "Sign-up verification emails go through Resend as well."
open_url "${DASH}/settings/auth"
step "Scroll to 'SMTP Settings' → Enable Custom SMTP."
step "Sender email: orders@tips-sd.com · Sender name: TIPS Beauty"
step "Host: smtp.resend.com · Port: 465 · Username: resend · Password: the Resend API key from stage 2."
step "Save. Under the Email provider settings keep 'Confirm email' ON."
pause "Press Enter once SMTP is saved."
write_env AUTH_SMTP_SET "$(date +%F)"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Supabase Auth: site URL and redirect URLs"
open_url "${DASH}/auth/url-configuration"
step "Site URL: ${STOREFRONT_URL}"
step "Redirect URLs — add each:"
say "    ${STOREFRONT_URL}/**"
say "    ${ADMIN_URL}/**"
say "    tipsbeauty://**"
say "    http://localhost:5173/**   (development)"
say "    http://localhost:5174/**   (development)"
pause "Press Enter once saved."
write_env AUTH_URLS_SET "$(date +%F)"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Staff order-alert recipients"
say "New-order alerts go to the addresses configured in the Admin Portal."
open_url "${ADMIN_URL}/settings"
note "(Not deployed yet? Run it locally: cd admin-portal && npm run dev → http://localhost:5174/settings)"
step "Log in as an admin → الإعدادات → add each staff email → save."
ask NOTIFICATION_EMAILS "Which addresses did you enter (comma-separated, for the record)?"
write_env NOTIFICATION_EMAILS "$NOTIFICATION_EMAILS"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Delete test data"
say "Testing left tagged rows that must not reach customers. Run this in the SQL editor:"
open_url "${DASH}/sql/new"
printf '\n'
say "delete from public.order_status_history where order_id in (select id from public.orders where customer_name like 'TEST-%');"
say "delete from public.notification_queue    where order_id in (select id from public.orders where customer_name like 'TEST-%');"
say "delete from public.payment_proofs        where order_id in (select id from public.orders where customer_name like 'TEST-%');"
say "delete from public.reviews               where order_id in (select id from public.orders where customer_name like 'TEST-%');"
say "delete from public.inventory_movements   where reference_id in (select id from public.orders where customer_name like 'TEST-%');"
say "delete from public.orders where customer_name like 'TEST-%';"
say "delete from public.drivers where name in ('QA E2E Driver', 'مندوب اختبار الخرطوم');"
say "delete from public.warehouse_inventory where warehouse_id in (select id from public.warehouses where name like 'QA E2E%');"
say "delete from public.warehouses where name like 'QA E2E%';"
printf '\n'
step "Then Authentication → Users: delete test-customer@tips-sd.com and test-admin@tips-sd.com."
warn "This is irreversible. Check Orders in the Admin Portal first if unsure."
if confirm "Have you run the cleanup and deleted the two test users?"; then
  write_env TEST_DATA_CLEANED "$(date +%F)"
else
  SKIPPED+=("Test-data cleanup (SQL above + delete the two test users)")
fi

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Rotate the database password"
say "The database password was shared in a chat transcript during the audit and must be replaced."
open_url "${DASH}/settings/database"
step "Scroll to 'Database password' → 'Reset database password' → generate → save it in your password manager."
note "Nothing in the apps uses this password; only the CLI and database tools do."
if confirm "Password rotated?"; then
  write_env DB_PASSWORD_ROTATED "$(date +%F)"
else
  SKIPPED+=("Rotate the database password (Project Settings → Database)")
fi

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Deploy the two apps"
say "Each app needs only two public env vars on its host (Vercel, Netlify, …):"
say "    VITE_SUPABASE_URL=${SUPABASE_URL}"
say "    VITE_SUPABASE_ANON_KEY=<Dashboard → Project Settings → API → anon public key>"
step "Storefront: build the repo root with 'npm run build' → publish dist/ at ${STOREFRONT_URL}"
step "Admin Portal: build admin-portal/ with 'npm run build' → publish dist/ at ${ADMIN_URL}"
step "Both are single-page apps: configure the host to rewrite every path to /index.html."
ask HOSTING_PROVIDER "Hosting provider used (for the record):"
write_env HOSTING_PROVIDER "$HOSTING_PROVIDER"

finish
